/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DeckIdIndexImport } from './routes/$deckId/index'
import { Route as DeckIdStudyIndexImport } from './routes/$deckId/study/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DeckIdIndexRoute = DeckIdIndexImport.update({
  id: '/$deckId/',
  path: '/$deckId/',
  getParentRoute: () => rootRoute,
} as any)

const DeckIdStudyIndexRoute = DeckIdStudyIndexImport.update({
  id: '/$deckId/study/',
  path: '/$deckId/study/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$deckId/': {
      id: '/$deckId/'
      path: '/$deckId'
      fullPath: '/$deckId'
      preLoaderRoute: typeof DeckIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/$deckId/study/': {
      id: '/$deckId/study/'
      path: '/$deckId/study'
      fullPath: '/$deckId/study'
      preLoaderRoute: typeof DeckIdStudyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$deckId': typeof DeckIdIndexRoute
  '/$deckId/study': typeof DeckIdStudyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$deckId': typeof DeckIdIndexRoute
  '/$deckId/study': typeof DeckIdStudyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$deckId/': typeof DeckIdIndexRoute
  '/$deckId/study/': typeof DeckIdStudyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$deckId' | '/$deckId/study'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$deckId' | '/$deckId/study'
  id: '__root__' | '/' | '/$deckId/' | '/$deckId/study/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckIdIndexRoute: typeof DeckIdIndexRoute
  DeckIdStudyIndexRoute: typeof DeckIdStudyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckIdIndexRoute: DeckIdIndexRoute,
  DeckIdStudyIndexRoute: DeckIdStudyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$deckId/",
        "/$deckId/study/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$deckId/": {
      "filePath": "$deckId/index.tsx"
    },
    "/$deckId/study/": {
      "filePath": "$deckId/study/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
